[build]
command = "npm run build"
publish = ".next"

[[plugins]]
package = "@netlify/plugin-nextjs"

[build.environment]
NODE_VERSION = "18"
NPM_FLAGS = "--legacy-peer-deps"

[[redirects]]
from = "/*"
to = "/.netlify/functions/next_server"
status = 200
force = true

[functions]
included_files = ["prisma/**"]

[functions]
node_bundler = "esbuild"
external_node_modules = ["@prisma/client", "@prisma/engines"]

[dev]
framework = "#custom"
command = "npm run dev"
targetPort = 3000
port = 8888
publish = "public"